she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newsStory'),
    path('<int:pk>/edit-story', views.UpdateStoryView.as_view(), name='editstory'),
    path('<int:pk>/delete-story', views.DeleteStoryView.as_view(), name='deletestory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

she_codes_news/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name='createAccount'),
    path('author/<int:pk>/', views.AuthorView.as_view(), name='author-detail')
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.URLField()
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='stories',
    )

    def __str__(self):
        return str(self.title)

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    pass #this is where I would put my own fields (like profile pic)

    def __str__(self):
        return self.username

  

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'image']
        widgets = {
            'pub_date': forms.DateInput(
                format=('%m/%d/%Y'),
                attrs={
                    'class': 'form',
                    'class': 'inputbox',
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class': 'form',
                    'class': 'inputbox'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form',
                    'class': 'inputbox',
                    'placeholder': 'Enter Comments Here'
                }
            )
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']



class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class AddStoryView(LoginRequiredMixin, generic.CreateView):
    login_url = '/users/login/'
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UpdateStoryView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    login_url = '/users/login/'
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/editStory.html'
    model = NewsStory

    def get_success_url(self):
        story_id= self.kwargs['pk']
        success_url = reverse_lazy('news:story', kwargs={'pk':
        story_id})
        return success_url

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class DeleteStoryView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    login_url = '/users/login/'
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/deleteStory.html'
    model = NewsStory

    def get_success_url(self):
        author_id= self.get_object().author.pk
        success_url = reverse_lazy('users:author-detail', kwargs={'pk':
        author_id})
        return success_url

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.order_by('-pub_date')
        return context
    


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm
from news.models import NewsStory

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'


class AuthorView(generic.DetailView):
    model = CustomUser
   
 
 

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% load static %}  

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}

{% load static %}  

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<p>Are you sure you want to delete this story?</p>

<a href="{% url 'news:index' %}">Home</a>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{object.title}} {{ object.content }}</p>
    <input type="submit" value="submit">
</form>



{% endblock %}

she_codes_news/news/templates/news/editStory.html
{% extends "base.html" %}

{% load static %}  

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<p> Edit Story</p>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}  

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content%}

     {% if user.is_authenticated %}
        <a href="{% url 'news:newsStory' %}">Write New Story</a>
    {% else %}
        <a href="{% url 'login' %}">Login to write a new story</a>
    {% endif %}


    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    {% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src="{{ story.image }}">
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
{% load static %}  

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}


<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        
            <img src="{{ story.image }}">
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4><a href="{% url 'users:author-detail' story.author.id %}">{{ story.author }}</a></h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Nicolette Heath">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if user.is_authenticated %}
        <a href="{% url 'users:author-detail' user.id %}">{{user.username}}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Register</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Create Account</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/customuser_detail.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <h2>{{ object.username }} Profile </h2>

    <p>Username: {{ object.username }}</p>
    <p>Email: {{ object.email }}</p>
{% else %}

    <h2>{{ object.username }} Profile </h2>

    <p>Email: {{ object.email }}</p>
    {% endif %}

{% if object %} 
    <h2>{{ object.get_full_name|default:object.username }}'s Stories</h2>
    {% for story in object.stories.all %}
    <div class="story-card" id="story-card-{{ position }}">
        <a href="{% url 'news:story' story.id %}">
            
                <img src="{{ story.image }}">
            <div class="story-card-text">
                <h3>{{ story.title }}</h3>
                <h4><a href="{% url 'users:author-detail' story.author.id %}">{{ story.author }}</a></h4>
                <h4>{{ story.pub_date }}</h4>
            </div>
        </a>

        {% if request.user.id == story.author.id %}
        <a href="{% url 'news:editstory' story.id %}">Edit this Story</a>
        <a href="{% url 'news:deletestory' story.id %}">Delete this Story</a>
        {% endif %}
    </div>
    {% endfor %}
{% else %}
    <p>This author has not written any stories yet.</p>
{% endif %}


{% endblock %}

she_codes_news/users/templates/users/userAccount.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <h2>Your Profile</h2>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
{% else %}
    <p>You need to log in.</p>

    {% endif %}

{% endblock %}